steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'container', 'clusters', 'get-credentials', 'CLUSTER_NAME', '--zone', 'asia-northeast1-c', '--project', '$PROJECT_ID' ]
  id: gcloud container clusters get-credentials
- name: 'alpine'
  args: ['./server/k8s/overlays/production/build.sh "server:${CIRCLE_SHA1}"']
  id: kustomize build
- name: 'gcr.io/cloud-builders/kubectl'
  args: [ 'apply', '-f', './server/k8s/manifest/prd-k8s.yaml' ]
  id: kubectl apply
