version: "3.7"
services:
  client:
    image: client
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    container_name: client
    depends_on:
      - server
    ports:
      - 8080:8080
  server:
    image: server
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    container_name: server
    expose:
      - 19003
