apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: prd
resources:
- ../../base
patchesStrategicMerge:
- client-deployment.yaml
images:
- name: client-deployment
  newName: asia.gcr.io/noticonn-test/k8s-grpc/client
  newTag: master
