apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: server
  name: server
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 19003
  selector:
    app: server
  type: ClusterIP
status:
  loadBalancer: {}

