apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-name
spec:
  template:
    spec:
      imagePullSecrets:
        - name: secret-name
      containers:
        - name: container-name
          imagePullPolicy: Always
