apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
spec:
  replicas: 2
  template:
    spec:
      imagePullSecrets:
        - name: secret-name
      containers:
        - name: container-name
