apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-k8s-client-deployment
  labels:
    app: k8s-client
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: grpc-k8s-client
          image: client-deployment
          ports:
            - containerPort: 8080
