apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: prd
resources:
- ../../base
patchesStrategicMerge:
- server-deployment.yaml
images:
- name: server-deployment
  newName: asia.gcr.io/noticonn-test/k8s-grpc/server
  newTag: master
