apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-k8s-server-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: grpc-k8s-server
          image: server-deployment
          ports:
            - containerPort: 19003
